### ISSUE TITLE
npm run build failure in repo

### ISSUE THREAD

**Issue by EMCP** [JRGEMCP/MAHRIO-HEADER#12]
If I just pull down the repo and run `npm run build` , I get some error about webpack not finding the `src/main.js`..?

```
~/Dev/git/JRGEMCP/MAHRIO-HEADER (master)$ npm run build
mahrio-header@1.0.0 /Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER
└── mahrio@1.3.0  (git+https://github.com/JRGEMCP/MAHRIO.git#5ae9827d5a32dbdbae213d6f00a43c47941b73e9)

  0% compilingEntryModuleNotFoundError: Entry module not found: Error: Can't resolve './src/main.js' in '/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER'
    at moduleFactory.create (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/webpack/lib/Compilation.js:391:29)
    at factory (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/webpack/lib/NormalModuleFactory.js:247:20)
    at resolver (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/webpack/lib/NormalModuleFactory.js:65:21)
    at asyncLib.parallel.e (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/webpack/lib/NormalModuleFactory.js:138:21)
    at /Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/async/dist/async.js:3861:9
    at /Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/async/dist/async.js:996:13)
    at /Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/async/dist/async.js:906:16
    at /Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/async/dist/async.js:3858:13
    at resolvers.normal.resolve (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/webpack/lib/NormalModuleFactory.js:130:23)
    at onError (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/tapable/lib/Tapable.js:252:11)
    at /Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/Resolver.js:168:10)
    at loggingCallbackWrapper (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/node_modules/tapable/lib/Tapable.js:252:11)
resolve './src/main.js' in '/Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER'
  using description file: /Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/package.json (relative path: .)
    using description file: /Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/package.json (relative path: ./src/main.js)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/src/main.js doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/src/main.js.js doesn't exist
      as directory
        /Users/emcp/Dev/git/JRGEMCP/MAHRIO-HEADER/src/main.js doesn't exist
~/Dev/git/JRGEMCP/MAHRIO-HEADER (master)$ 

```

**Comment by JesusGuerrero** [comment]
mahrio-header does not have a build process. It's an Angular2 module that is simply included via imports from clients

**Comment by EMCP** [comment]
@JesusGuerrero how were you modifying the src properly then?

or is there no style/client code in here.. just models and services?

**Comment by JesusGuerrero** [comment]
there is only shared module code and one main component (header). The repo does not have a webpack build. The current one there was for local testing

**Comment by EMCP** [comment]
perhaps we can clean up what's in this repo then.. ?  Or would that break things?

**Comment by EMCP** [comment]
I want to add CI integration to this component.. if it doesn't have a working `npm run build` then I need to know what alternative way to verify the component works at the command line base

**Comment by EMCP** [comment]
CI has been added, and build is failing.  closing since this is semi expected.. but request we fix sometime later.
